### ISSUE TITLE
Option to make the build directory a relative symlink - problem with Vagrant

### ISSUE THREAD

**Issue by manubing** [kraftwagen/kraftwagen#21]
Hello,

When using Vagrant, if Kraftwagen is used on the guest OS, the ```build``` directory will not be accessible on the host OS:

```
$ls -l
total 112
-rw-r--r--   1 manu  staff    188  1 jul 11:43 INSTALL.md
-rw-r--r--   1 manu  staff   2897 27 jui 11:27 Vagrantfile
lrwxrwxrwx   1 manu  staff     44 28 jui 12:06 build -> /home/vagrant/project/builds/20130628-100609
drwxrwxr-x  13 manu  staff    442 28 jui 12:56 builds
...
```

`/home/vagrant` does not exists on the host OS. Obviously, same problem if we lauch the build on the host OS, the guest can't access the build symlink.

How about an option to make the symlink to the `build` dir relative?

Thanks

**Comment by matglas** [comment]
@rolfvandekrol or @manubing has anything happend on this issue since July 2013?

**Comment by manubing** [comment]
No, I am now using an Ansible playbook to deploy projects in vagrant or on servers.

Closing for now.

**Comment by jerbob92** [comment]
I added relative symlinks in #40
