### ISSUE TITLE
Make Kraftwagen Drush-6.x compatible

### ISSUE THREAD

**Issue by winmillwill** [kraftwagen/kraftwagen#25]
API change in drush make_download_DOWNLOAD_TYPE()

signature was:

`make_download_DOWNLOAD_TYPE($name, $download, $download_location)`

but is now

`make_download_DOWNLOAD_TYPE($name, $type, $download, $download_location)`

Need to either update https://github.com/kraftwagen/kraftwagen/blob/master/process.make.inc#L14 or document that we must use an older version of drush (I'm using 8.x-6.0rc4)

**Comment by ErikGreve** [comment]
My problem is that with drush 6.x the project specific make-file in the src-dir isn't picked up by kw-build.

AFAIK there's no (stable) drush 5.x version for Windows, and on my FreeBSD machine I always have to be very careful not to automatically update drush to 6.x (no 'portupgrade -a' for me :-().
Could you make Kraftwagen fully drush 6.x-compatible, please?

**Comment by rolfvandekrol** [comment]
I currently run Drush 6.7-dev locally, without any issues. Builds are running just fine.

**Comment by barraponto** [comment]
I'm running Drush 8.0-dev with no issues.

**Comment by sebas5384** [comment]
@barraponto good to hear!
