### ISSUE TITLE
Rollback command

### ISSUE THREAD

**Issue by matglas** [kraftwagen/kraftwagen#41]
It would be nice to have a rollback command where you can return back to the previous build.

**Comment by rolfvandekrol** [comment]
Having a command that allows you to select the build, instead of just choosing the most recent build, would be great. 

I would prefer not to use the word rollback for this, because this is actually not a proper rollback. A proper rollback would be to undo migrations, undo the effects of manifests, disable and uninstall modules that are not in the build anymore, and probably some more. Kraftwagen does not do those things (and probably never will, because of the limits of what be achieved in Drupal), therefore, I wouldn't use the word rollback for this.

**Comment by bighappyface** [comment]
What would be a good name for a command that lets you select a build? `kw-set-build <dirname>`?

**Comment by rolfvandekrol** [comment]
There is already a command that changes the `build` symlink to point to a specific build. This command accepts a full path to the build as parameter. 

This command can also be used to activate a previous build if you specify the path to a previous build.

I'm not sure whether that is already enough to fullfil the use case of @matglas or if we need something a bit higher level that figures out the path to the previous build.

**Comment by bighappyface** [comment]
The `kw-activate-build` command is cool but could use some love in terms of determining the real path. Here is an example:

```bash
// From within "src" dir
bin/drush kw-activate-build "$(pwd)/../builds/20150320-202808"
// results in symlink build -> ./src/../builds/20150320-202808/
```

In addition to documenting `kw-activate-build` and adding it to the command list (shown when running an empty `drush`), perhaps it can be modified to list available builds when the directory parameter isn't given:

```bash
drush kw-activate-build 

Choose build:
1. 20150320-202808
2. 20150320-213742
3. 20150323-110710 (current)
```

**Comment by matglas** [comment]
We do need to make it a public command. And the list option sounds very usefull. An addition would be to store a previous file in the builds folder to remember what the previous build was after you ran kw-b. We might not need a activate-previous but with the list feature and a mention what was the previous active build you can choose easily.

**Comment by rolfvandekrol** [comment]
This sounds like a plan. So we make `kw-activate-build` public, give it some love to determine the right path, and we extend it to provide a nice choosing interface when not given a path to a build. Who's going to make a PR for this?

**Comment by matglas** [comment]
I will try to take a stab at it between work. :)

Op woensdag 25 maart 2015 heeft Rolf van de Krol notifications@github.com
het volgende geschreven:

**Comment by matglas** [comment]
Is there a kraftwagen option to get the builds directory?

**Comment by matglas** [comment]
I created a pull request but don't know how to attach it to this issue.
